apiVersion: v1
kind: Secret
metadata:
  name: payments-db
  namespace: default
type: Opaque
stringData:
  DATABASE_HOST: payments-db.default.svc.cluster.local
  DATABASE_USER: payments_app
  DATABASE_PASSWORD: supersecret123
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-kubelet-api-lab
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:stable
    env:
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: payments-db
          key: DATABASE_HOST
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: payments-db
          key: DATABASE_USER
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: payments-db
          key: DATABASE_PASSWORD
