## We previously deployed global policy that denies everything by default
## Now we will allow only restricted access
## In the first step, we allow all Egress to busybox only

- name: Implement targeted policy
  hosts: k8s-playground
  vars:
    policy_path: /tmp/calico-allow-egress.yaml
  tasks:


  ## ADD  POLICY to allow all egress from busybox pod
    
  - name: Ensure tmp dir exists
    ansible.builtin.file:
      path: /tmp
      state: directory
      mode: '0755'

  - name: Render targeted policy manifest
    ansible.builtin.template:
      src: calico-allow-egress.yaml.j2
      dest: "{{  policy_path }}"
      mode: '0644'

  - name: Delete policy in case already exists
    ansible.builtin.command:
      cmd: kubectl delete --force -f "{{  policy_path }}"
    failed_when: false
  
  - name: Apply policy
    ansible.builtin.command:
      cmd: kubectl create -f "{{  policy_path }}"
  
  ## TEST public internet now reachable
  - name: Test public internet
    ansible.builtin.command: kubectl exec --namespace={{ calico_ns }} access --  wget -qO- https://docs.tigera.io/pod-connection-test.txt
    register: public_internet_response
    changed_when: false
    
  - name: Log public internet response
    ansible.builtin.debug: 
      msg: "{{ public_internet_response.stdout }}"
    changed_when: false

  - name: Check public page query response 
    ansible.builtin.assert:
      that:
        - "'successfully connected' in public_internet_response.stdout"
      fail_msg: "Public internet not reached"
    changed_when: false


  ## Nginx from busybox should fail, because default deny policy blocks ingress traffic to nginx 
  - name: Query nginx from busybox
    ansible.builtin.command: kubectl exec --namespace={{ calico_ns }} access -- wget -qO- http://nginx
    register: nginx_http_response
    changed_when: false
    failed_when: false
  
  
  - name: Log nginx response
    ansible.builtin.debug: 
      msg: "{{ nginx_http_response.stderr }}"
    changed_when: false

  - name: Check error code
    ansible.builtin.assert:
      that:
        - nginx_http_response.rc != 0
        - >
          'bad address' in nginx_http_response.stderr or
          'timed out' in nginx_http_response.stderr or
          'failed' in nginx_http_response.stderr or
          'refused' in nginx_http_response.stderr
      fail_msg: "Nginx is still reachable"
    changed_when: false



