## Allow ingress traffic to nginx pods from busybox pods

- name: Implement targeted policy
  hosts: k8s-playground
  vars:
    policy_path: "{{ calico_tmp_folder }}/calico-allow-ingress.yaml"
  tasks:


  ## ADD  POLICY to allow all ingress to nginx from busybox pod
  - name: Ensure tmp dir exists
    ansible.builtin.file:
      path: "{{ calico_tmp_folder }}"
      state: directory
      mode: '0755'

  - name: Render targeted policy manifest
    ansible.builtin.template:
      src: calico-allow-ingress.yaml.j2
      dest: "{{  policy_path }}"
      mode: '0644'

  - name: Delete policy in case already exists
    ansible.builtin.command:
      cmd: kubectl delete --force -f "{{  policy_path }}"
    failed_when: false
  
  - name: Apply policy
    ansible.builtin.command:
      cmd: kubectl create -f "{{  policy_path }}"
  

  ## Nginx from busybox should be reachable now
  - name: Query nginx from busybox
    ansible.builtin.command: kubectl exec --namespace={{ calico_ns }} access -- wget -qO- http://nginx
    register: nginx_http_response
    changed_when: false


  - name: Log nginx response
    ansible.builtin.debug: 
      msg: "{{ nginx_http_response.stdout }}"
    changed_when: false

  - name: Check Nginx welcome page 
    ansible.builtin.assert:
      that:
        - "'Welcome to nginx' in nginx_http_response.stdout"
      fail_msg: "Nginx not reached"
    changed_when: false



