apiVersion: v1
kind: Config
clusters:
- name: "{{ authentication_lab_cluster_name }}"
  cluster:
    certificate-authority-data: "{{ authentication_lab_cluster_ca_data }}"
    server: "{{ authentication_lab_cluster_server }}"
contexts:
- name: "alice@{{ authentication_lab_cluster_name }}"
  context:
    cluster: "{{ authentication_lab_cluster_name }}"
    user: alice
current-context: "alice@{{ authentication_lab_cluster_name }}"
users:
- name: alice
  user:
    client-certificate-data: "{{ authentication_lab_certificate_data }}"
    client-key-data: "{{ authentication_lab_private_key_data }}"