apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alice-pod-reader
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-pod-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alice-pod-reader
subjects:
- kind: User
  name: Alice
  apiGroup: rbac.authorization.k8s.io